USE [master]
GO

/****** Object:  Database [vault_identity]    Script Date: 14/07/2022 20:45:04 ******/
CREATE DATABASE [vault_identity]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vault_identity', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\vault_identity.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vault_identity_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\vault_identity_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vault_identity].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vault_identity] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vault_identity] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vault_identity] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vault_identity] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vault_identity] SET ARITHABORT OFF 
GO

ALTER DATABASE [vault_identity] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vault_identity] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vault_identity] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vault_identity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vault_identity] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vault_identity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vault_identity] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vault_identity] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vault_identity] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vault_identity] SET  ENABLE_BROKER 
GO

ALTER DATABASE [vault_identity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vault_identity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vault_identity] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vault_identity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vault_identity] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vault_identity] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [vault_identity] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vault_identity] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vault_identity] SET  MULTI_USER 
GO

ALTER DATABASE [vault_identity] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vault_identity] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vault_identity] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vault_identity] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vault_identity] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vault_identity] SET QUERY_STORE = OFF
GO

USE [vault_identity]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [vault_identity] SET  READ_WRITE 
GO


