USE [master]
GO

CREATE DATABASE [vault_library]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vault_library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vault_library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vault_library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vault_library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vault_library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vault_library] SET ARITHABORT OFF 
GO

ALTER DATABASE [vault_library] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vault_library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vault_library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vault_library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vault_library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vault_library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vault_library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vault_library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vault_library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vault_library] SET  ENABLE_BROKER 
GO

ALTER DATABASE [vault_library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vault_library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vault_library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vault_library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vault_library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vault_library] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [vault_library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vault_library] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vault_library] SET  MULTI_USER 
GO

ALTER DATABASE [vault_library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vault_library] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vault_library] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vault_library] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vault_library] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vault_library] SET QUERY_STORE = OFF
GO

USE [vault_library]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [vault_library] SET  READ_WRITE 
GO


